README.in
rt-app is no longer maintained in gbagnoli's github.  Update the URL.
=> Update github URL of the repository

doc/tutorial.txt, src/rt-app.c, src/rt-app_parse_config.c, src/rt-app_types.h
"yield" event simply calls pthread_yield()
This has a special meaning for SCHED_DEADLINE tasks
=> rt-app: add support for "yield" event

src/rt-app_parse_config.c
No need to retrieve the cpuset via json_object_get_array(). We use
json_object_array_get_idx() instead to get the cpus of the cpuset
instead.
Signed-off-by: Dietmar Eggemann <dietmar.eggemann@arm.com>
Acked-by: Juri Lelli <juri.lelli@arm.com>
=> Remove unsued cpuset in parse_thread_data()

doc/tutorial.txt
With the provided command I get this error from ./configure:
```
checking whether the C compiler works... no
configure: error: in `/home/brendan/sources/rt-app':
configure: error: C compiler cannot create executables
See `config.log' for more details
```
This seems to be because the "libs/" part is bogus.
=> doc: Fix ./configure command in tutorial.txt

src/rt-app_parse_config.c
In json-c-0.12 is_error() is defined in bits.h which is exported via
json.h. However, json-c's master branch contains commit d4e81f9ec827
which declares bits.h deprecated and removes the export via json.h.
Replace the use of is_error() with its trivial implementation to be
able to get rid of this single dependency towards the deprecated
bits.h.
This fixes an issue introduced by commit 17dd99c72a12 ("Clean-up header
file inferno") which removed #include <json-c/bits.h> from
src/rt-app_parse_config.c.
Cc: Olav Haugan <ohaugan@codeaurora.org>
Signed-off-by: Dietmar Eggemann <dietmar.eggemann@arm.com>
Acked-by: Vincent Guittot < vincent.guittot@linaro.org>
=> Do not use json-c's is_error() any more

doc/examples/tutorial/example7.json, doc/tutorial.txt, src/rt-app.c, src/rt-app_parse_config.c, src/rt-app_types.h, src/rt-app_utils.c
I wanted a way to provide a sync point for two threads where it didn't
matter which one got there first - the first thread to reach the sync
point would wait, and the last would just signal and continue.
Using a bare lock/signal/wait/unlock on both sides results in the second
thread being suspended briefly immediately after it signals which is
not desirable when trying to mimic existing thread activation patterns.
If we don't use bare signal/wait then it doesn't need to be restricted
to just 2 threads, you can sync an arbitrary number (>1) of threads at
a given point in a use case by including barrier events in them.
This effect could be achieved with a pthread_barrier, but there is no
officially sanctioned way to cancel a barrier sync event once it has
started and no way to tell if any …
=> Add Barrier Sync Primitive

doc/examples/tutorial/example8.json, doc/tutorial.txt, src/rt-app.c, src/rt-app_parse_config.c, src/rt-app_types.h
Allow setting of cpusets at all levels of the spec.
Signed-off-by: Olav Haugan <ohaugan@codeaurora.org>
Tested-by: Dietmar Eggemann <dietmar.eggemann@arm.com>
Reviewed-by: Dietmar Eggemann <dietmar.eggemann@arm.com>
Tested-by: Viresh Kumar <viresh.kumar@linaro.org>
Acked-by: Juri Lelli <juri.lelli@arm.com>
Signed-off-by: Stephen Boyd <stephen.boyd@linaro.org>
=> rtapp: Add broader support for specifying cpusets

src/rt-app_parse_config.c
According to documentation the default value of 'loop' is -1, but the
threads without a loop field runs only once and stops.
Fix it.
Fixes: 3bda96e6e664 ("add phase feature")
Signed-off-by: Viresh Kumar <viresh.kumar@linaro.org>
Acked-by: Vincent Guittot <vincent.guittot@linaro.org>
=> rt-app: Fix broken 'loop' default value

configure.ac
It is time we bump version to 1.0 (as major development happened and lot
of new features got merged).
Also update Copyright information to reflect current maintainers.
Signed-off-by: Juri Lelli <juri.lelli@arm.com>
=> configure: bump version to 1.0 and update copyright

doc/tutorial.txt, src/rt-app.c, src/rt-app_parse_config.c
loop property handling appears to be broken (i.e., loop at thread level is ignored and always defaults to -1 when there isn't a phases object).
Fix it by also sanitising code a bit.
=> Fix loop property handling

configure.ac
return an error if lib json-c is  not present so you don't try to compile
=> rt-app/json-c: missing json-c returns error

src/rt-app.c, src/rt-app_parse_config.c
These are a few very minor cleanups to fix build warnings found with clang and static analysis with cppcheck.
=> Minor clean ups to fix build warnings

doc/tutorial.txt
A tab instead of a space was interpreted as an error by the configure
script.
=> Tab instead of space typo in cross compiling instructions

src/rt-app_utils.h
The semicolon after the "while(0)" in defining the language trick:
do { \
rtapp_log_to(stderr, LOG_LEVEL_ERROR, "<error> ", msg, ##args); \
} while (0);
is not necessary, and represents an error when using logging macros like
log_debug() in the following scenarios:
if (condition)
log_debug("condition true");
else
log_debug("condition false");
=> Bugfix for using logging macros code blocks without brackets

src/rt-app_parse_config.c
A thread without events to run is useless and must be considered as an
error
Reported-by: Alessio Balsini <alessio.balsini@arm.com>
=> rt-app: fix error handling of threads without events

src/rt-app_types.h
Commit ("rt-app: add per phase set priority event") moved the priority
related data into struct _sched_data_t. The struct _phase_data_t also
contains a sched_data_t pointer so there is no need to have an
additional int sched_prio data element.
Signed-off-by: Dietmar Eggemann <dietmar.eggemann@arm.com>
=> Remove unsued sched_prio from struct _phase_data_t

configure.ac, src/rt-app_args.c
Since it often happens to distribute already (cross)compiled rt-app
executables, it is useful to add a way to check the release version of
the software.
This patch adds the software version and build information to the
executable, that can be accessed with the arguments -v or --version
with the following syntax:
[PACKAGE] [git describe --tags HEAD] ([BUILD DATE])
$ rt-app -v|--version
rt-app v1.0-29-g6f10c0c (2017-12-06 16:39:38 GMT)
Moreover, a simple help is returned when using the arguments -h or
--help.
=> Return simple help and version

src/rt-app.c
Use pthread_setschedparam instead of setpriority for setting task into
CFS class. setpriority only changes the CFS priority but not the scheduling
class.
When a task has been set to fifo class, it can't move back to other class
=> fix sched_other policy setting

src/rt-app_parse_config.c
Some newer versions of json-c library stopped defining TRUE and FALSE
and this causes a compile issue.
Fix it my defining those if not yet defined by json-c (to be back and
forward compatible with the library).
=> parse_config: Define TRUE and FALSE if not already defined by json-c.

src/rt-app_args.c, src/rt-app_utils.c, src/rt-app_utils.h
proposed implementation of https://github.com/scheduler-tools/rt-app/issues/59
=> add option to change debug/log level per invocation

README.in, autogen.sh, doc/tutorial.txt
build/installation info should be in a more obvious location, autogen shouldn't ask to run ./configure if it fails.
=> doc: move build information into README.in, autogen.sh: exit on error

src/rt-app_utils.h
Align forward declaration and definition return types of timespec_
to_nsec() function, as current misalignment is problematic on some
archs.
=> utils: Fix timespec_to_nsec() return type

doc/examples/tutorial/example9.json, doc/tutorial.txt, src/rt-app.c, src/rt-app_parse_config.c, src/rt-app_types.h
To be able to test scheduler behaviour when forking a new thread, we need to be able to fork half way through the experiment.
This pull request adds a new 'fork' event to fork a new thread at a selected point of time rather just at rt-app startup. The new forked threads doesn't accept phases for simplicity. And there's a hard limit of 1024 forks to keep the resource allocation static at rt-app start rather than dynamically allocate at runtime which could 'interfere' with the experiment.
The pull request also fixes a typo in tutorial.txt which states that the default value of lock_pages is false but it is actually true.
I still need to update tutorial.txt to include the new fork event, but first want to make sure the approach is acceptable.
Thanks.
=> Fork support

doc/tutorial.txt, src/rt-app.c, src/rt-app_parse_config.c, src/rt-app_types.h, src/rt-app_utils.c
This adds support for SCHED_IDLE scheduling policy.
This locally defines SCHED_IDLE macro, which is incorrect but build was
failing without it and I am not sure how to fix that. The arch specific
sched.h headers (like /usr/include/aarch64-linux-gnu/bits/sched.h)
define them only if __USE_GNU is defined.
Signed-off-by: Viresh Kumar <viresh.kumar@linaro.org>
=> rt-app: Add support for SCHED_IDLE policy

doc/examples/tutorial/example10.json, doc/examples/tutorial/example11.json, doc/tutorial.txt, src/Makefile.am, src/rt-app.c, src/rt-app_parse_config.c, src/rt-app_taskgroups.c, src/rt-app_taskgroups.h, src/rt-app_types.h, src/rt-app_utils.h
The taskgroups support works currently for cgroupv1 (legacy)
hierarchies. It can be optionally configured by specifying
--with-taskgroups as a build parameter (see README.in).
A configuration example is given in doc/tutorial.txt.
For now an rt-app binary w/ taskgroup support only allows SCHED_NORMAL
policy. An rt-app binary w/o taskgroups support ignores any taskgroup
related name/value pairs in the json file.
Tested on x86_64 and arm64.
Signed-off-by: Dietmar Eggemann <dietmar.eggemann@arm.com>
=> Add taskgroups support for SCHED_OTHER tasks

autogen.sh
The BUILD_DATE and VERSION are generated when the configure script is
created. However, by default autoreconf only remakes those files that
are older than their sources. Thus, when we add some new patches on an
already existing rt-app tree (i.e. without touching configure.in) a new
build does not get an updated "--version" output.
Force autoreconf to consider all files obsolete, so that every new:
autogen.sh && configure && make
cycle generates updated version strings.
Signed-off-by: Patrick Bellasi <patrick.bellasi@arm.com>
=> rtapp: Force update date/build_version on autoreconf

doc/examples/browser-long.json, doc/examples/browser-short.json, doc/examples/cpufreq_governor_efficiency/calibration.json, doc/examples/cpufreq_governor_efficiency/dvfs.json, doc/examples/mp3-long.json, doc/examples/mp3-short.json, doc/examples/video-long.json, doc/examples/video-short.json, src/rt-app_parse_config.c
The "ftrace" JSON option has always been considered optional and, by default, no
ftrace events was genererated if that option was not specified.
With the addition of the ftrace category support in:
commit a2d7d8c571eb ("ftrace: Add support for ftrace categories and make them easy to parse")
and specifically with code to grant backward compatibility for the now
deprecated bool type, the JSON parser complains if a value for "ftrace" is not
specified, thus failing to be completely backward compatibile.
Fix that by adding a check on "ftrace" missing and allowing the code to smoothly
fall-back to the default behavior.
Signed-off-by: Patrick Bellasi <patrick.bellasi@arm.com>
=> rtapp/config: Fix "ftrace" for backward support

doc/tutorial.txt, src/rt-app_parse_config.c
The events of  thetask object are parsed only once even if several
instances will be then created.
barrier.waiting must add all instances of the task that will sync.
Similar init can't be done for fork event has we don't know in advance
how many forkees will be created which means that fork and barrier can't
be used in the same task description. The solution would be to set an init
value to the barrier resource in the "resources" object but that's a
dedicated dev.
=> barrier: fix waiting event with multi instances tasks

src/rt-app_parse_config.c
rt-app displays the spurious and useless :
[rt-app] <notice> [json]         util_min: -1, util_max: -1
for each and every threads node that is parsed even if no clamp values
have been specified in the json node.
Remove this useless print
=> rt-app:config: remove spurious log_notice

src/rt-app.c
Wrong logs file when using gnuplot. Taking as reference the following config file:
```
{
"tasks": {
"task3": {
"runtime": 3000,
"timer": {
"period": 1000000,
"mode": "absolute",
"ref": "unique"
}
},
"task1": {
"runtime": 19000,
"timer": {
"period": 1000000,
"mode": "absolute",
"ref": "unique"
}
}
},
"global": {
"duration": 2,
"default_policy": "SCHED_DEADLINE",
"pi_enabled": false,
"lock_pages": false,
"logdir": "./rtapp-log",
"log_basename": "rt-app",
"log_mode": "file",
"gnuplot": true
}
}
```
The names of the log files are: `rt-app-task1-1.log  rt-app-task3-0.log`, but taking a look at the `rt-app-period.plot` file we have: 
```
plot "rt-app-task3-0-0.log" u ($5/1000):4 w l title "thread [task3-0] (SCHED_DEADLINE)", "rt-app-task1-1-1.log" u ($5/1000):4 w l title "thread [task1-1] …
```
=> Fix gnuplot logs file name for single thread task

src/rt-app.c
When running rt-app on older android kernels (4.19 and before),
sched_setattr() syscall fails with -E2BIG error code. These kernels
don't have uclamp support. The kernel returns an error when the
new fields (in this case uclamp attributes) not known to kernel
are non zero. To fix this initialize the sched_attr structure to 0.
Signed-off-by: Pavankumar Kondeti <pkondeti@codeaurora.org>
=> rt-app: Fix sched_setattr() failures with older kernels

src/rt-app_parse_config.c
When the JSON configuration is not matching the expected schema, the
current behavior is to print an error log and carry on with a 0-duration
run event. This is quite harmful as execution therefore continues
(potentially unnoticed), with a workload that is not at all what the
user wanted.
This is especially important when:
* many phases are involved. The error can be lost in the flow
* on automated setups: if no one is there to watch the log, critical
errors like malformed input must be translated to a negative exit
status.
Since there is no valid reason to provide an ill-formed (and therefore
meaningless) input, exit when this case is detected, which will make the
problem obvious to the user.
closes https://github.com/scheduler-tools/rt-app/issues/82
=> config: parse_task_event_data(): Bail on malformed config

src/rt-app.c, src/rt-app_types.h
Some build errors prevented building rt-app in Alpine Linux. These modifications should allow building.
=> Alpine linux fixes

README.in
Support for SCHED_DEADLINE is the default since
commit af279433a58e ("Always build with deadline").
The parameter does not do anything anymore, so remove it.
Signed-off-by: Christian Loehle <cloehle@posteo.de>
=> Remove mentioning of with-deadline in documentation

doc/examples/custom-slice.json, doc/tutorial.txt, src/rt-app.c
Kernels starting with 6.12 have a new feature which allows requesting
a custom slice length on a task while using one of `SCHED_OTHER`,
`SCHED_BATCH` or `SCHED_EXT`. The interface was created by reusing the
existing `sched_attr::sched_runtime` parameter.
Similarly, this patch series reuses the existing interface (dl-runtime)
to allow users to experiment with the new custom slice feature.
Test output (kernel 6.13.0-rc1-00060-g7d9da040575b):
rt-app -l 100 doc/examples/custom-slice.json
[rt-app] <notice> [0] Starting with SCHED_OTHER policy with priority -19
[rt-app] <notice> [1] Starting with SCHED_DEADLINE policy with priority 0
[rt-app] <debug> [0] setting scheduler SCHED_OTHER nice=-19 runtime=100000000
[rt-app] <debug> [1] setting scheduler SCHED_DEADLINE exec 200000000, deadline …
=> Add sched_runtime support for SCHED_OTHER

configure.ac, src/rt-app_args.c, src/rt-app_parse_config.c, src/rt-app_types.h, src/rt-app_utils.c
Starting with GNU libc 2.41, the sched_getattr and sched_setattr functions, and the sched_attr structure are provided in sched.h. This causes a conflict with the definition in libdl.
The configure script already checks for the sched_setattr function, but then the logic to compile and link libdl was wrong, as it is not possible to directly check the HAVE_SCHED_SETATTR with AM_CONDITIONAL. In addition the dl_syscalls.h include file needs to be guarded, and a few include files that were indirectly included by this file not to be done explictly.
=> Fix build with GNU libc 2.41

src/rt-app_taskgroups.c, src/rt-app_types.h
The build on Fedora 42 fails with two errors, I'm not sure if the
problem is in the combination of the shipped glibc-2.41 and gcc-15.1.1
(https://github.com/scheduler-tools/rt-app/pull/136 is not enough).
`SCHED_DEADLINE` is not defined if `<linux/sched.h>` is not included and
`rt-app_taskgroups.c` requires `<unistd.h>` which is not defined with
`HAVE_SCHED_SETATTR`.
=> Fix build on Fedora 42
